# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Android',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_registered', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('desktop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Desktop')),
            ],
        ),
    ]
