# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='base_date',
            field=models.DateField(auto_now=True),
        ),
    ]
