# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktop',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
