# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_desktop_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktop',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='desktop',
            name='uuid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
