# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_dailyactivity_base_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivity',
            name='base_date',
            field=models.DateField(),
        ),
    ]
