# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 02:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20170625_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_key',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
