# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_client_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client_Key',
            new_name='Client_Key_Hash',
        ),
        migrations.RenameField(
            model_name='client_key_hash',
            old_name='key',
            new_name='key_hash',
        ),
    ]
