# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 13:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0003_auto_20170711_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktop',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
