# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20170625_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_key',
            name='pub_key',
            field=models.CharField(max_length=2047),
        ),
    ]
