# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 22:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20170701_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop',
            name='timezone',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
