# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 00:10
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0005_auto_20170701_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='base_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='timestamp',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
