# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20170703_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyactivity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='desktop',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='desktop',
            name='user',
        ),
        migrations.DeleteModel(
            name='DailyActivity',
        ),
    ]
